package pojo;
// Generated Oct 26, 2020 2:22:11 AM by Hibernate Tools 4.3.1

import dao.admin;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;



/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;

    public Admin() {
    }

    public Admin(int id, String username, String password) {
       this.id = id;
       this.username = username;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    public void save()
    {
        admin pdao=new admin();
        pdao.addAdmin(this);
    }

    public void delete()
    {    
        admin pdao=new admin();
        pdao.deleteAdmin(username);
    }

    public List<Admin> getbyid()
    { 
        admin pdao=new admin();
        List<Admin> prod=pdao.getbyID(username);
        password=prod.get(0).password;
        return prod;
    }

    public List<Admin> getallrecords()
    {
        admin pdao=new admin();
        List<Admin> prod=pdao.retrieveAdmin();
        return prod;
    }

    public void update()
    {
        admin pdao=new admin();
        pdao.updateAdmin(this);
    }
    
    public String validatelogin()
    { 
        try {
            admin pdao=new admin();
            List<Admin> prod=pdao.validateLogin(username, password);
            username=prod.get(0).username;
            password=prod.get(0).password;
            
            FacesContext context = FacesContext.getCurrentInstance();
            if(username != null) {
                context.getExternalContext().getSessionMap().put("username", username);
                return "success";
            }
            else {
                return "error";
            }
        }
        catch(Exception ex) {
            return "error";
        }
        //return prod;
    }
    
    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "index";
    }




}


