package pojo;
import dao.kelas;
import java.util.List;
import javax.faces.bean.ManagedBean;
// Generated Oct 26, 2020 2:22:11 AM by Hibernate Tools 4.3.1



/**
 * Kelas generated by hbm2java
 */
@ManagedBean
public class Kelas  implements java.io.Serializable {


     private Integer id;
     private String nama;

    public Kelas() {
    }

    public Kelas(String nama) {
       this.nama = nama;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    
    public void save()
    {
        kelas pdao=new kelas();
        pdao.addKelas(this);
    }

    public void delete()
    {    
        kelas pdao=new kelas();
        pdao.deleteKelas(id);
    }

    public List<Kelas> getbyid()
    { 
        kelas pdao=new kelas();
        List<Kelas> prod=pdao.getbyID(id);
        nama=prod.get(0).nama;
        return prod;
    }

    public List<Kelas> getallrecords()
    {
        kelas pdao=new kelas();
        List<Kelas> prod=pdao.retrieveKelas();
        return prod;
    }

    public void update()
    {
        kelas pdao=new kelas();
        pdao.updateKelas(this);
    }




}


