package pojo;
// Generated Oct 26, 2020 2:22:11 AM by Hibernate Tools 4.3.1

import dao.login;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;




/**
 * Login generated by hbm2java
 */
@ManagedBean
public class Login  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;

    public Login() {
    }

    public Login(String email, String password) {
       this.email = email;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
     public void save()
    {
        login pdao=new login();
        pdao.addLogin(this);
    }

    public void delete()
    {    
        login pdao=new login();
        pdao.deleteLogin(id);
    }

    public List<Login> getbyid()
    { 
        login pdao=new login();
        List<Login> prod=pdao.getbyID(id);
        email=prod.get(0).email;
        password=prod.get(0).password;
        return prod;
    }

    public List<Login> getallrecords()
    {
        login pdao=new login();
        List<Login> prod=pdao.retrieveLogin();
        return prod;
    }

    public void update()
    {
        login pdao=new login();
        pdao.updateLogin(this);
    }
    
    public String validatelogin()
    { 
        try {
            login pdao=new login();
            List<Login> prod=pdao.validateLogin(email, password);
            email=prod.get(0).email;
            password=prod.get(0).password;
            
            FacesContext context = FacesContext.getCurrentInstance();
            if(email != null) {
                context.getExternalContext().getSessionMap().put("email", email);
                return "success";
            }
            else {
                return "error";
            }
        }
        catch(Exception ex) {
            return "error";
        }
        //return prod;
    }
    
    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "index";
    }


}


