package pojo;
// Generated Oct 25, 2020 7:39:12 PM by Hibernate Tools 4.3.1

import dao.registForm;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * Regist generated by hbm2java
 */
@ManagedBean
public class Regist  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String numtelp;
     private String sosmed;
     private String univ;
     private String nim;

    public Regist() {
    }

    public Regist(String name, String address, String numtelp, String sosmed, String univ, String nim) {
       this.name = name;
       this.address = address;
       this.numtelp = numtelp;
       this.sosmed = sosmed;
       this.univ = univ;
       this.nim = nim;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getNumtelp() {
        return this.numtelp;
    }
    
    public void setNumtelp(String numtelp) {
        this.numtelp = numtelp;
    }
    public String getSosmed() {
        return this.sosmed;
    }
    
    public void setSosmed(String sosmed) {
        this.sosmed = sosmed;
    }
    public String getUniv() {
        return this.univ;
    }
    
    public void setUniv(String univ) {
        this.univ = univ;
    }
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }

    public void save()
    {
        registForm pdao=new registForm();
        pdao.addForm(this);
    }

    public void delete()
    {    
        registForm pdao=new registForm();
        pdao.deleteForm(id);
    }

    public List<Regist> getbyid()
    { 
        registForm pdao=new registForm();
        List<Regist> prod=pdao.getbyID(id);
        name=prod.get(0).name;
        address=prod.get(0).address;
        numtelp=prod.get(0).numtelp;
        sosmed=prod.get(0).sosmed;
        univ=prod.get(0).univ;
        nim=prod.get(0).nim;
        return prod;
    }

    public List<Regist> getallrecords()
    {
        registForm pdao=new registForm();
        List<Regist> prod=pdao.retrieveForm();
        return prod;
    }

    public void update()
    {
        registForm pdao=new registForm();
        pdao.updateForm(this);
    }



}