package pojo;
// Generated Oct 25, 2020 7:39:12 PM by Hibernate Tools 4.3.1

import dao.signUp;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * Signup generated by hbm2java
 */
@ManagedBean
public class Signup  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String name;
     private String password;

    public Signup() {
    }

    public Signup(String email, String name, String password) {
       this.email = email;
       this.name = name;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
        public void save()
    {
        signUp pdao=new signUp();
        pdao.addSignup(this);
    }

    public void delete()
    {    
        signUp pdao=new signUp();
        pdao.deleteSignup(id);
    }

    public List<Signup> getbyid()
    { 
        signUp pdao=new signUp();
        List<Signup> prod=pdao.getbyID(id);
        email=prod.get(0).email;
        name=prod.get(0).name;
        password=prod.get(0).password;
        return prod;
    }

    public List<Signup> getallrecords()
    {
        signUp pdao=new signUp();
        List<Signup> prod=pdao.retrieveSignup();
        return prod;
    }

    public void update()
    {
        signUp pdao=new signUp();
        pdao.updateSignup(this);
    }


}